---
- name: Ensure we have the 2.4 RPM AAP software
  register: download_aap_tarball
  until: download_aap_tarball is not failed
  retries: 5
  delay: 20
  ansible.builtin.get_url:
    url: https://api.access.redhat.com/management/v1/images/{{ checksum }}/download
    headers:
      accept: application/json
      Authorization: Bearer {{ access_token.json.access_token }}
    dest: ~/aap24r.tar.gz
    checksum: "sha256: {{ checksum }}"
    group: root
    owner: root
    mode: '0644'

- name: Checking to see if we have already opened the 2.4 rpm software
  register: my_test
  ansible.builtin.stat:
    path: ~/aap24r_was_opened

- name: Ensure the 2.4 RPM aap bundle is opened up
  when: my_test.stat.exists == false
  ansible.builtin.unarchive:
    src: ~/aap24r.tar.gz
    dest: ~/
    remote_src: true

- name: Create a file to let us know if we have already opened up the 2.4 rpm aap software
  when: my_test.stat.exists == false
  ansible.builtin.copy:
    content: ""
    dest: ~/aap24r_was_opened
    owner: root
    group: root
    mode: '0444'

- name: Ensure we have the RPM AAP 2.4 rpm software directory
  register: aap_bundle_dir
  changed_when: false
  ansible.builtin.shell: ls -d ansible-automation-platform-setup-2.4-* | grep -v tar.gz
  args:
    chdir: ~/

- name: Make copy of the 2.4 rpm software to original name
  changed_when: false
  ansible.builtin.command: "cp aap24r.tar.gz {{ aap_bundle_dir.stdout }}.tar.gz"
  args:
    chdir: ~/

- name: Creating the new 2.4 inventory file
  ansible.builtin.template:
    src: legacy_aap_inventory_controller_file.j2
    dest: "~/{{ aap_bundle_dir.stdout }}/inventory"
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Copy the vault file into place for the 2.4 install
  ansible.builtin.copy:
    src: vault.yml
    dest: "~/{{ aap_bundle_dir.stdout }}/vault.yml"
    owner: root
    group: root
    mode: "0644"
    decrypt: false