---
- name: Setting up the Ansible Automation Platform install
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    keys:
      - name: ansible-svc
        key: ./files/public_keys/ansible-svc
    users:
      - name: ansible-svc
        sudoers_account: true
        user_comment: Service Account
        # user_password: vaulted
        user_home: /home/ansible-svc

  vars_files:
    - ./files/distributions.yml
    - ./files/vault.yml

  vars_prompt:
    - name: controller_url
      prompt: What is your server's fully qualified domain name?
      private: false

    - name: aap_distro
      prompt: |-

        Legend:
          r = rpm, c = containerized, b = bundle

        "Which Ansible Automation Platform (AAP) distro to use 2.4r or 2.4c or 2.4cb 2.5r or 2.5c or 2.5cb? default: 2.5c"
      private: false
      default: "2.5c"

  tasks:

    - name: Get diskspace
      register: diskspace
      changed_when: false
      ansible.builtin.command:
        cmd: lsblk -f

    - name: Get podman version
      register: podman
      changed_when: false
      ansible.builtin.command:
        cmd: podman --version

    - name: Get our distribution info
      loop: "{{ distributions }}"
      when: item['name'] == aap_distro
      ansible.builtin.set_fact:
        checksum: "{{ item['aap_sha_value'] }}"
        rh_distro: "{{ item['rh_distro'] }}"
        architecture: "{{ item['architecture'] }}"
        name: "{{ item['name'] }}"

    - name: Print out system checks
      ansible.builtin.debug:
        msg:
          - "Our stand alone controller_url: {{ controller_url }}"
          - "Total system memory: {{ ansible_memtotal_mb }} mb should be >= 16 gigs"
          - "Total cpu count: {{ ansible_processor_vcpus }} should be >= 4"
          - "Red Hat Enterprise Linux: {{ ansible_distribution }} {{ ansible_facts['distribution_version'] }} {{ ansible_facts['userspace_architecture'] }} >= 9.2"
          - Diskspace >= 60 >= 3000 IOPS
          - "{{ diskspace['stdout_lines'] }}"
          - "{{ podman['stdout_lines'] }}"
          - "We are installing {{ aap_distro }} AAP the checksum is {{ checksum }}"

    - name: Check in with user
      ansible.builtin.pause:
        prompt: Please confirm that it is safe to proceed. Press return to continue. Press Ctrl+c and then "a" to abort

    - name: Ensure we have a access token the Red Hat Customer portal
      register: access_token
      until: access_token is not failed
      retries: 1
      delay: 20
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type: refresh_token
          client_id: rhsm-api
          refresh_token: "{{ offline_token }}"

    - name: Import tasks needed for 2.4 rpm software install
      when: aap_distro == "2.4r"
      ansible.builtin.import_tasks:
        file: ./files/24r.yml

    - name: Import tasks needed for 2.5 rpm software install
      when: aap_distro == "2.5r"
      ansible.builtin.import_tasks:
        file: ./files/25r.yml

    - name: Import tasks needed for all containerized installs
      when: aap_distro == "2.4c" or
        aap_distro == "2.4cb" or
        aap_distro == "2.5c" or
        aap_distro == "2.5cb"
      ansible.builtin.import_tasks:
        file: ./files/container_all.yml

    - name: Import tasks needed for 2.4 containerized install
      when: aap_distro == "2.4c"
      ansible.builtin.import_tasks:
        file: ./files/24c.yml

    - name: Import tasks needed for 2.4 containerized install bundle
      when: aap_distro == "2.4cb"
      ansible.builtin.import_tasks:
        file: ./files/24cb.yml

    - name: Import tasks needed for 2.5 containerized install
      when: aap_distro == "2.5c"
      ansible.builtin.import_tasks:
        file: ./files/25c.yml

    - name: Import tasks needed for 2.5 containerized install bundle
      when: aap_distro == "2.5cb"
      ansible.builtin.import_tasks:
        file: ./files/25cb.yml
