- name: Setting up the Ansible Automation Platform install
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../files/distributions.yml
  vars_prompt:
    - name: controller_url
      prompt: What is your server's fully qualified domain name?
      private: false

    - name: aap_distro
      prompt: "Which Ansible Automation Platform distro to use 2.4 or 2.5? default: '2.5'"
      private: false
      default: '2.5'

  tasks:

    - name: Print out the fqdn
      ansible.builtin.debug:
        msg: "{{ controller_url }}"

    - name: Print aap_distro
      loop: "{{ distributions }}"
      #when: item['name'] == 'aap_distro'
      ansible.builtin.debug:
        msg: "{{ item['aap_sha_value'] }}"

    - name: Print out total memory
      ansible.builtin.debug:
        var: ansible_memtotal_mb

    - name: Print out CPU count
      ansible.builtin.debug:
        var: ansible_processor_count

    - name: Print out Ansible Distribution
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Print out Ansible distribution_version
      ansible.builtin.debug:
        var: ansible_facts['distribution_version']

    - name: Print out Architecture
      ansible.builtin.debug:
        var: ansible_facts['userspace_architecture']

    - name: Print out disk partitions
      loop: "{{ ansible_devices['nvme0n1']['partitions']['keys']() | list }}"
      # when: ansible_devices['nvme0n1']['partitions'][item]['links']['labels'] == "root"
      ansible.builtin.debug:
        msg: "{{ ansible_devices['nvme0n1']['partitions'][item]['size'] }}"

    - name: Print out disk partitions
      loop: "{{ ansible_devices['nvme0n1']['partitions']['keys']() | list }}"
      # when: ansible_devices['nvme0n1']['partitions'][item]['links']['labels'] == 'root'
      ansible.builtin.debug:
        msg: "{{ ansible_devices['nvme0n1']['partitions'][item]['links']['labels'] }}"
