- name: Testing stuff
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    aap_bundle_sha_value: 21c0a27c809c1a98402bdb7605b67b62174b2f54155bad4146c1824be0830f70
    partitions: "{{ ansible_devices | dict2items | selectattr('key','match','^nvme0n1.*') |
                    map(attribute='value.partitions') }}"
    keys: "{{ partitions | json_query('[].keys(@)') | flatten }}"
    values: "{{ partitions | json_query('[].*.{holders: holders, size: size}') | flatten }}"
    dictionary: "{{ dict(keys|zip(values)) }}"
  vars_prompt:
    - name: fqdn
      prompt: What is your fully qualified domain name?
      private: false

  tasks:

    - name: Print out the fqdn
      ansible.builtin.debug:
        msg: "{{ fqdn }}"

    - name: Print out total memory
      ansible.builtin.debug:
        var: ansible_memtotal_mb

    - name: Print out CPU count
      ansible.builtin.debug:
        var: ansible_processor_count

    - name: Print out Ansible Distribution
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Print out Ansible distribution_version
      ansible.builtin.debug:
        var: ansible_facts['distribution_version']

    - name: Print out Architecture
      ansible.builtin.debug:
        var: ansible_facts['userspace_architecture']

    - name: Print out disk keys
      ansible.builtin.debug:
        msg: "{{ ansible_devices.keys() | list }}"

    - name: Print out disk partitions
      loop: "{{ ansible_devices.keys() | list }}"
      ansible.builtin.debug:
        msg: "{{ ansible_devices[item]['partitions']['keys']() | list }}"

    - name: Print out disk partitions
      ansible.builtin.debug:
        var: partitions

    - name: Print out disk partitions
      ansible.builtin.debug:
        var: keys

    - name: Print out disk partitions
      ansible.builtin.debug:
        var: values

    - name: Print out disk partitions
      ansible.builtin.debug:
        var: dictionary
