- name: Testing stuff
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    aap_bundle_sha_value: 21c0a27c809c1a98402bdb7605b67b62174b2f54155bad4146c1824be0830f70
  vars_prompt:
    - name: fqdn
      prompt: What is your fully qualified domain name?
      private: false

  tasks:

    - name: Print out the fqdn
      ansible.builtin.debug:
        msg: "{{ fqdn }}"

    - name: Print out total memory
      ansible.builtin.debug:
        var: ansible_memtotal_mb

    - name: Print out CPU count
      ansible.builtin.debug:
        var: ansible_processor_count

    - name: Print out Ansible Distribution
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Print out Ansible distribution_version
      ansible.builtin.debug:
        var: ansible_facts['distribution_version']

    - name: Print out Architecture
      ansible.builtin.debug:
        var: ansible_facts['userspace_architecture']

    - name: Get disk info
      ansible.builtin.set_fact:
        my_disks: "{{ ansible_devices.keys() |
                        reject('match', '^loop(.*)$') |
                        list }}"

    - name: Print out disk info
      loop: my_disks
      ansible.builtin.debug:
        var: item
